app = 'yourappname'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'


[[mounts]]
  source = 'n8n_vol'
  destination = '/home/node/.n8n'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/healthz'
    protocol = 'http'


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
