# fly.toml app configuration file generated for n8n-app-flyin on 2025-08-16T13:56:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'n8n-app-flyin'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'n8n_vol'
  destination = '/home/node/.n8n'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'true'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/healthz'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
